### ISSUE TITLE
codeforamerica.org is timing out with Lighthouse

### ISSUE THREAD

**Issue by cy-by** [codeforamerica/speedlify-cfa#2]
This is happening with both `v3` and `v4` of the `performance-leaderboard` package.

Going to monitor [issue 44](https://github.com/zachleat/speedlify/issues/44) and [issue 46](https://github.com/zachleat/speedlify/issues/46) in the original repo.
 
```
11:10:37 AM: (Site 1 of 5, run 1 of 3): https://www.codeforamerica.org
11:12:50 AM: Logged an error with https://www.codeforamerica.org:  LighthouseError [LHError]: PROTOCOL_TIMEOUT
11:12:50 AM:     at Timeout.<anonymous> (/opt/build/repo/node_modules/lighthouse/lighthouse-core/gather/driver.js:322:21)
11:12:50 AM:     at listOnTimeout (internal/timers.js:554:17)
11:12:50 AM:     at processTimers (internal/timers.js:497:7) {
11:12:50 AM:   code: 'PROTOCOL_TIMEOUT',
11:12:50 AM:   friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)',
11:12:50 AM:   lhrRuntimeError: true,
11:12:50 AM:   protocolMethod: 'Runtime.evaluate'
11:12:50 AM: }
```

**Comment by davidhund** [comment]
FYI @coltborg : I ran into the same issue and adding the `--disable-dev-shm-usage` chromeFlag fixed it…
See: https://github.com/zachleat/speedlify/issues/44#issuecomment-993441252
